services:
  productservice.api:
    image: ${DOCKER_REGISTRY-}productserviceapi
    build:
      context: .
      dockerfile: ProductService.API/Dockerfile
   
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: